<?php
    define("ERROR_SERVICE_TEMPORARY_ERROR", "Спробуйте повторити запит пізніше.");
    define("ERROR_EMPTY_KOMDEBT_PAYMENT", "Повинна оплачуватись хоча б одна послуга");
    define("ERROR_FIELD_EMPTY_ERROR_MSG", "Поле «{FIELD}» не повинно бути порожнім.");
    define("ERROR_FIELD_SPESIAL_CHARS_ERROR_MSG", " поле не може містити спеціальні символи.");
    define("ERROR_INCORRECT_EMAIL_ERROR_MSG", "Адреса електронної пошти невірна.");
    define("ERROR_FIELD_MIN_ERROR_MSG", " не може бути менше, ніж ");
    define("ERROR_FIELD_MAX_ERROR_MSG", " не може бути більше, ніж ");
    define("ERROR_LOGIN_ALREADY_EXIST", "Такий логін вже існує.");
    define("ERROR_LOGIN_FIELDS_EMPTY", "Данi для авторизації не вказано.");
    define("ERROR_LOGIN_ERROR_MSG", "Данi для авторизації невірні.");
    define("ERROR_SECURITY_CODE", "Невірний перевірочний код.");
    define("ERROR_CURRENT_PASSWORD", "Дiйсний пароль невірний.");
    define("ERROR_EMAIL_DOESNOT_EXIST", "Користувач з такою адресою електронної пошти не існує.");
    define("ERROR_EMAIL_ALREADY_EXIST", "Користувач з такою адресою електронної вже існує.");
    define("ERROR_PHONE_ALREADY_EXIST", "Користувач з таким номером мобільного телефону вже існує.");
    define("ERROR_SET_NEWPASSWORD", "Неможливо задати новий пароль.");
    define("ERROR_SENDING_MAIL", "Неможливо відправити повідомлення.");
    define("ERROR_DATE", "Помилка дати.");
    // define("ERROR_GET_STREET", "Помилка у виведенні списку вулиць.");
    // define("ERROR_GET_HOUSE", "Помилка у виведенні списку будинків.");
    define("ERROR_GET_FLAT", "Помилка при отриманні квартири.");
    define("ERROR_GETTING_DEBT", "Немає платежів за вибраний місяць.");
    define("ERROR_ADDRESS_ALREADY_EXIST", "Квартира вже додана.");
    define("ERROR_TRANSACTION_NOT_SUCCESS", 'Транзакція не оплачена.');
    define("ERROR_TOO_MANY_FLATS", "Занадто багато доданих об'єктів");
    define("ERROR_TRANSACTION_NEW", 'Транзакція має статус «нова» (ще не оплачена).');
    define("ERROR_PASSWORD_NOT_CONCUR", " Поля «пароль» і «повторити пароль» не збігаються.");
    define("ERROR_PASSWORD_TOO_SHORT", "Пароль повинен бути не менше 6 символів.");
    define("ERROR_INVALID_ACCOUNT", "Невірний номер свого особового рахунку.");
    define("ERROR_TRANSACTION_FOUND", 'Транзакція не знайдена.');
    define("ERROR_INCORRECT_PHONE_FORMAT_ERROR_MSG", "Неправильний формат телефону.");
    define("ERROR_USER_NOT_LOGGED_IN", "Користувач повинен бути авторизований");
    define("ERROR_NOT_FIND_FLAT", "Запитуваний об'єкт не знайдено");
    define("ERROR_INVALID_ZERO_PAYMENT", "Платіж не може бути порожнім");
